name: Docker Image - Beta

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create image off.'
        required: true
        default: 'main'
      tag:
        description: 'Name of the docker tag to create.'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'ai-beta' }}

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: huoda0711
          password: ${{ secrets.FLOWISE_SERCET }}

      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: huoda0711/flowise:Flowise
          no-cache: true
